### ISSUE TITLE
Улучшить отображение элементов интерфейса на "старых" устройствах

### ISSUE THREAD

**Issue by basilred** [shri-team5/pepo#125]
Из известного: флексбокс не работает в Сафари на iOS 8 и старых Андроидах (версии 3 и ниже).

**Comment by Grimfrid** [comment]
Судя по http://caniuse.com/#search=flex  должно все работать с приставкой -webkit (она у нас есть), почему все едет - не понятно

**Comment by basilred** [comment]
@Grimfri Я возьму на себя, есть в наличии оба старых устройства. Разберусь с проблемой.

**Comment by basilred** [comment]
https://github.com/shri-team5/pepo/pull/141
