### ISSUE TITLE
Расположение аватара в твитах разной высоты. Баг или фича?

### ISSUE THREAD

**Issue by basilred** [shri-team5/pepo#126]
Аватарка в твитах разной высоты находится на разном расстоянии от верхней границы блока. Зависит от высоты блока. Баг или фича?
<img width="325" alt="screen shot 2016-09-04 at 14 22 54" src="https://cloud.githubusercontent.com/assets/413033/18230654/6665a100-72ab-11e6-8981-300283458830.png">

**Comment by Grimfrid** [comment]
баг
