### ISSUE TITLE
Перенести кнопку создания твита вниз

### ISSUE THREAD

**Issue by Grimfrid** [shri-team5/pepo#135]
Например как в Any.Do или Gmail на андроиде

**Comment by basilred** [comment]
Это хорошая идея, учитывая замечания, которые мы слышали на защите относительно удобства расположения элементов.

**Comment by basilred** [comment]
Меня глючит или кнопка выглядит сплющеной на мобильном?
![screenshot_2016-09-12-01-08-14](https://cloud.githubusercontent.com/assets/413033/18420965/5c59d4e2-7887-11e6-8605-f4d2a1b677b3.png)
