### ISSUE TITLE
Поправить вёрстку location в ленте

### ISSUE THREAD

**Issue by basilred** [shri-team5/pepo#188]
<img width="292" alt="screen shot 2016-09-16 at 19 25 07" src="https://cloud.githubusercontent.com/assets/413033/18593337/a0a7fc68-7c43-11e6-9512-20620caedbd0.png">

**Comment by Grimfrid** [comment]
#192

**Comment by basilred** [comment]
Не уверен, что нужно обрезать текст по фиксированной ширине. На широких экранах вполне можно показать без подрезки или использовать относительный размер. Например, на iPhone 6s Plus куча свободного места:

<img width="294" alt="screen shot 2016-09-17 at 00 47 12" src="https://cloud.githubusercontent.com/assets/413033/18602317/dfce7a3e-7c70-11e6-8428-eedee28711ae.png">
