### ISSUE TITLE
При загрузке фотографии большого размера вываливает 413 ошибку nginx

### ISSUE THREAD

**Issue by Grimfrid** [shri-team5/pepo#194]
413 Request Entity Too Large

**Comment by Grimfrid** [comment]
@basilred а пока можем сдеать это: http://ruhighload.com/post/%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B0+413+Request+Entity+Too+Large

**Comment by basilred** [comment]
@Grimfri, повесь на меня, я поправлю.

**Comment by basilred** [comment]
Увеличил размер до 4 МБайт.
