### ISSUE TITLE
Реализовать предпросмотр ссылки в твите

### ISSUE THREAD

**Issue by vorobeez** [shri-team5/pepo#9]
- [x] Подключить внешнюю библиотеку
- [x] Показывать в блоке твита (и всех лентах?) карточку ссылки (url брать из спец.поля объекта твита)
- [x] Показывать карточку ссылки при вводе в textarea нового твита

В некоторых полях `url` объекта `ogImage` хранятся относительные, а не абсолютные пути. В таком случае картинка не приедет. **Нужно пофиксить**.
## 

[про meta-тэги](https://stackoverflow.com/questions/11616697/how-to-use-og-meta-tag-for-facebook-share)

**Comment by basilred** [comment]
https://github.com/shri-team5/pepo/pull/208
